version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gog-lite/
    binary: gog-lite
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

homebrew_casks:
  - name: gog-lite
    repository:
      owner: kubot64
      name: homebrew-tap
    homepage: "https://github.com/kubot64/gog-lite"
    description: "CLI for AI agents to operate Gmail / Google Calendar / Google Docs"
    binaries:
      - gog-lite
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gog-lite"]
          end
